server:
  port: 8007

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true